// frontend-client/src/pages/home.jsx
import React, {useEffect, useState} from "react";
import {Button, Col, Form, Row, Table} from "react-bootstrap";
import userService from "../services/userService";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

function Home() {

    const [username, setUsername] = useState("");
    const [password, setPassword] = useState("");
    const [users, setUsers] = useState([]);

    useEffect(() => {
        initSocket();
    }, []);

    function initSocket() {
        let connection = new WebSocket("ws://localhost:8080/Chat-war/ws/chat"); // 'chat' should be individual person's username
        connection.onopen = function () {
            console.log("Socket is open");
        }

        connection.onclose = function () {
            connection = null;
        }

        connection.onmessage = function (msg) {
            const data = msg.data.split("!");
            if(data[0] === "LOGGEDIN") {
                let users = [];
                data[1].split("|").forEach(user => {
                    if (user) {
                        let userData = user.split(",");
                        users.push({
                            username: userData[0],
                            password: userData[1]
                        })
                    }
                });
                setUsers(users);
            } else {
                toast(data[1]);
            }
        }

    }

    function register() {
        userService.register({
            username: username,
            password: password
        });
    }

    function login() {
        userService.login({
            username: username,
            password: password
        });
    }

    function getUsers() {
        userService.getUsers();
    }

    const userRows = users.map((user, key) => (
        <tr>
            <td>{user.username}</td>
            <td>{user.password}</td>
        </tr>
    ))

    return (
        <div>
            <Row><Col md={{span: 4, offset: 4}}>
                <Row className={'mt-5 mb-2'}>
                    <Form.Control placeholder="Enter username"
                                  value={username} onChange={e => setUsername(e.target.value)}/>
                </Row>
                <Row className={'mb-3'}>
                    <Form.Control type="password" placeholder="Enter password"
                                  value={password} onChange={e => setPassword(e.target.value)}/>
                </Row>
                <Row className={'mb-2'}>
                    <Button variant="primary" onClick={register}>Sign Up</Button>
                </Row>
                <Row className={'mb-2'}>
                    <Button variant="primary" onClick={login}>Log In</Button>
                </Row>
                <Row className={'mb-2'}>
                    <Button variant="outline-secondary" onClick={getUsers}>List all logged-in users</Button>
                </Row>
                <Row>
                    <Table striped bordered hover>
                        <thead>
                        <tr>
                            <th>Username</th>
                            <th>Password</th>
                        </tr>
                        </thead>
                        <tbody>
                            {userRows}
                        </tbody>
                    </Table>
                </Row>
            </Col></Row>
            <ToastContainer/>
        </div>
    );
}

export default Home;

// frontend-client/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from 'src/app/model/user-model';
import { UserService } from 'src/app/services/user.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  user = new User();
  users: string[] = [];

  constructor(private userService: UserService) { }

  ngOnInit(): void {
    this.initSocket();
  }

  initSocket() {
    let connection = new WebSocket("ws://localhost:8080/Chat-war/ws/chat"); // 'chat' should be individual person's username
    connection.onopen = function () {
      console.log("Socket is open");
    }

    /*connection.onclose = function () {
      connection = null;
    }*/

    connection.onmessage = function (msg) {
      const data = msg.data.split("!");
      if (data[0] === "LOGGEDIN") {
        //users = [];
        data[1].split("|").forEach((user: string) => {
          if (user) {
            let userData = user.split(",");
            /*this.users.push({
              username: userData[0],
              password: userData[1]
            });*/
          }
        });
      }
      else if (data[0] === "REGISTER") {
        //toast(data[1]);
        alert('register');
      }
      else {
        //toast(data[1]);
        alert('login');
      }
    }

  }

  register() {
    this.userService.register(this.user);
  }

  login() {
    this.userService.login(this.user);
  }

  getUsers() {
    this.userService.getUsers();
  }

}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>

<body>
    <div class=" d-flex justify-content-center">
        
        <form class="w-25 mt-5">
            <h1>Welcome</h1>
            <br><br>
            <!-- Username input -->
            <div class="form-outline mb-4">
                <input name="username" type="username" id="username" class="form-control" [(ngModel)]="user.username"/>
                <label class="form-label" for="username">Username</label>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
                <input name="password" type="password" id="password" class="form-control"  [(ngModel)]="user.password"/>
                <label class="form-label" for="password">Password</label>
            </div>

            <!-- Submit button -->
            <div class="row">
                <button type="button" class="btn btn-primary btn-block mb-4" (click)="register()">Register</button>
                <br>
                <button type="button" class="btn btn-primary btn-block mb-4" (click)="login()">Login</button>
            </div>
        </form>
    </div>
</body>

</html>
